package actions

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"budget_tracker/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Transaction)
// DB Table: Plural (transactions)
// Resource: Plural (Transactions)
// Path: Plural (/transactions)
// View Template Folder: Plural (/templates/transactions/)

// TransactionsResource is the resource for the Transaction model
type TransactionsResource struct {
	buffalo.Resource
}

// List gets all Transactions. This function is mapped to the path
// GET /transactions
// List gets all Transactions. This function is mapped to the path
// GET /transactions
func (v TransactionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	transactions := &models.Transactions{}
	u := c.Value("current_user").(*models.User)

	// Base Query
	q := tx.PaginateFromParams(c.Params())
	q = q.Where("user_id = ?", u.ID)

	// Filter Params
	month := c.Param("month")
	year := c.Param("year")

	if month != "" && year != "" {
		// Postgres specific date extraction
		// Note: 'extract(month from transaction_date)' returns 1-12
		q = q.Where("extract(month from transaction_date) = ?", month).
			Where("extract(year from transaction_date) = ?", year)

		c.Set("filterMonth", month)
		c.Set("filterYear", year)

		// Calculate Stats for this filtered view
		// We need a fresh query for stats as 'q' is paginated
		var stats []struct {
			Type   string  `db:"type"`
			Amount float64 `db:"total"`
		}
		// Sum amounts grouped by type
		// Using raw query for aggregation
		err := tx.RawQuery("SELECT type, SUM(amount) as total FROM transactions WHERE user_id = ? AND extract(month from transaction_date) = ? AND extract(year from transaction_date) = ? GROUP BY type", u.ID, month, year).All(&stats)

		if err == nil {
			var income, expense float64
			for _, s := range stats {
				if s.Type == "Income" {
					income = s.Amount
				} else if s.Type == "Expense" {
					expense = s.Amount
				}
			}
			c.Set("filteredIncome", income)
			c.Set("filteredExpense", expense)
			c.Set("filteredMargin", income-expense)
		}
	}

	// Order by date desc
	q = q.Order("transaction_date desc")

	// Retrieve Transactions
	if err := q.All(transactions); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("pagination", q.Paginator)
		c.Set("transactions", transactions)
		return c.Render(http.StatusOK, r.HTML("transactions/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(transactions))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(transactions))
	}).Respond(c)
}

// Show gets the data for one Transaction. This function is mapped to
// the path GET /transactions/{transaction_id}
func (v TransactionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	u := c.Value("current_user").(*models.User)
	if err := tx.Where("user_id = ?", u.ID).Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("transaction", transaction)

		return c.Render(http.StatusOK, r.HTML("transactions/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(transaction))
	}).Respond(c)
}

// Create adds a Transaction to the DB. This function is mapped to the
// path POST /transactions
func (v TransactionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// Bind transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	u := c.Value("current_user").(*models.User)
	transaction.UserID = u.ID

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("transaction", transaction)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("transactions/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "transaction.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/transactions/%v", transaction.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(transaction))
	}).Respond(c)
}

// Update changes a Transaction in the DB. This function is mapped to
// the path PUT /transactions/{transaction_id}
func (v TransactionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	u := c.Value("current_user").(*models.User)
	if err := tx.Where("user_id = ?", u.ID).Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("transaction", transaction)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("transactions/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "transaction.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/transactions/%v", transaction.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(transaction))
	}).Respond(c)
}

// Destroy deletes a Transaction from the DB. This function is mapped
// to the path DELETE /transactions/{transaction_id}
func (v TransactionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	u := c.Value("current_user").(*models.User)
	if err := tx.Where("user_id = ?", u.ID).Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(transaction); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "transaction.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/transactions")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(transaction))
	}).Respond(c)
}

// New renders the form for creating a new Transaction.
// This function is mapped to the path GET /transactions/new
func (v TransactionsResource) New(c buffalo.Context) error {
	c.Set("transaction", &models.Transaction{
		TransactionDate: time.Now(),
	})
	return c.Render(http.StatusOK, r.HTML("transactions/new.plush.html"))
}

// Edit renders a edit form for a Transaction.
// This function is mapped to the path GET /transactions/{transaction_id}/edit
func (v TransactionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	u := c.Value("current_user").(*models.User)
	if err := tx.Where("user_id = ?", u.ID).Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("transaction", transaction)
	return c.Render(http.StatusOK, r.HTML("transactions/edit.plush.html"))
}
