package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"budget_tracker/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Transaction)
// DB Table: Plural (transactions)
// Resource: Plural (Transactions)
// Path: Plural (/transactions)
// View Template Folder: Plural (/templates/transactions/)

// TransactionsResource is the resource for the Transaction model
type TransactionsResource struct {
	buffalo.Resource
}

// List gets all Transactions. This function is mapped to the path
// GET /transactions
func (v TransactionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	transactions := &models.Transactions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Transactions from the DB
	if err := q.All(transactions); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("transactions", transactions)
		return c.Render(http.StatusOK, r.HTML("transactions/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(transactions))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(transactions))
	}).Respond(c)
}

// Show gets the data for one Transaction. This function is mapped to
// the path GET /transactions/{transaction_id}
func (v TransactionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("transaction", transaction)

		return c.Render(http.StatusOK, r.HTML("transactions/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(transaction))
	}).Respond(c)
}

// Create adds a Transaction to the DB. This function is mapped to the
// path POST /transactions
func (v TransactionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// Bind transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("transaction", transaction)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("transactions/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "transaction.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/transactions/%v", transaction.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(transaction))
	}).Respond(c)
}

// Update changes a Transaction in the DB. This function is mapped to
// the path PUT /transactions/{transaction_id}
func (v TransactionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Transaction to the html form elements
	if err := c.Bind(transaction); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(transaction)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("transaction", transaction)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("transactions/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "transaction.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/transactions/%v", transaction.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(transaction))
	}).Respond(c)
}

// Destroy deletes a Transaction from the DB. This function is mapped
// to the path DELETE /transactions/{transaction_id}
func (v TransactionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Transaction
	transaction := &models.Transaction{}

	// To find the Transaction the parameter transaction_id is used.
	if err := tx.Find(transaction, c.Param("transaction_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(transaction); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "transaction.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/transactions")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(transaction))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(transaction))
	}).Respond(c)
}
