package actions

import (
	"fmt"
	"math/rand"
	"net/http"
	"strconv"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"budget_tracker/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (User)
// DB Table: Plural (users)
// Resource: Plural (Users)
// Path: Plural (/users)
// View Template Folder: Plural (/templates/users/)

// UsersResource is the resource for the User model
type UsersResource struct {
	buffalo.Resource
}

// List gets all Users. This function is mapped to the path
// GET /users
func (v UsersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	users := &models.Users{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Users from the DB
	if err := q.All(users); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("users", users)
		return c.Render(http.StatusOK, r.HTML("users/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(users))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(users))
	}).Respond(c)
}

// Show gets the data for one User. This function is mapped to
// the path GET /users/{user_id}
func (v UsersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty User
	user := &models.User{}

	// To find the User the parameter user_id is used.
	if err := tx.Find(user, c.Param("user_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("user", user)

		return c.Render(http.StatusOK, r.HTML("users/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(user))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(user))
	}).Respond(c)
}

// Create adds a User to the DB. This function is mapped to the
// path POST /users
func (v UsersResource) Create(c buffalo.Context) error {
	// Allocate an empty User
	user := &models.User{}

	// Bind user to the html form elements
	if err := c.Bind(user); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := user.Create(tx)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("user", user)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("users/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		// Generate OTP
		rand.Seed(time.Now().UnixNano())
		otp := strconv.Itoa(rand.Intn(900000) + 100000)
		user.OTPCode = otp
		user.OTPExpiresAt = time.Now().Add(10 * time.Minute)
		user.IsVerified = false

		// Save OTP tokens to DB (update the user we just created)
		if err := tx.Update(user); err != nil {
			return err
		}

		// SIMULATE EMAIL SENDING
		fmt.Printf("\n\n========================================\n")
		fmt.Printf("SENDING OTP TO %s: %s\n", user.Email, otp)
		fmt.Printf("========================================\n\n")

		// If there are no errors set a success message
		c.Flash().Add("success", "Please check your email for the verification code.")
		c.Session().Set("pre_verification_user_id", user.ID)

		// and redirect to the verify page
		return c.Redirect(http.StatusSeeOther, "/verify-otp")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(user))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(user))
	}).Respond(c)
}

// Update changes a User in the DB. This function is mapped to
// the path PUT /users/{user_id}
func (v UsersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty User
	user := &models.User{}

	if err := tx.Find(user, c.Param("user_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind User to the html form elements
	if err := c.Bind(user); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(user)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("user", user)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("users/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "user.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/users/%v", user.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(user))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(user))
	}).Respond(c)
}

// Destroy deletes a User from the DB. This function is mapped
// to the path DELETE /users/{user_id}
func (v UsersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// AUTH CHECK: Ensure only self-deletion
	currentUserID := c.Session().Get("current_user_id")
	targetUserID := c.Param("user_id")

	if currentUserID == nil || fmt.Sprintf("%v", currentUserID) != targetUserID {
		c.Flash().Add("danger", "You are not authorized to delete this account.")
		return c.Redirect(http.StatusSeeOther, "/")
	}

	// Allocate an empty User
	user := &models.User{}

	// To find the User the parameter user_id is used.
	if err := tx.Find(user, targetUserID); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// VERIFY OTP
	otpInput := c.Request().FormValue("OTP")
	if user.OTPCode != otpInput {
		c.Flash().Add("danger", "Invalid OTP. Account deletion cancelled.")
		return c.Redirect(http.StatusSeeOther, "/account/delete/confirm/%s", user.ID)
	}

	if err := tx.Destroy(user); err != nil {
		return err
	}

	// Clear session after deletion
	c.Session().Clear()

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", "Account deleted successfully.")

		// Redirect to the home page
		return c.Redirect(http.StatusSeeOther, "/")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(user))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(user))
	}).Respond(c)
}

// RequestDeleteOTP generates an OTP and sends it to the user for account deletion
func (v UsersResource) RequestDeleteOTP(c buffalo.Context) error {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// AUTH CHECK
	currentUserID := c.Session().Get("current_user_id")
	targetUserID := c.Param("user_id")

	c.Logger().Infof("DEBUG: RequestDeleteOTP - CurrentUser: %v (Type: %T), TargetUser: %s", currentUserID, currentUserID, targetUserID)

	if currentUserID == nil || fmt.Sprintf("%v", currentUserID) != targetUserID {
		c.Flash().Add("danger", "Unauthorized.")
		return c.Redirect(http.StatusSeeOther, "/")
	}

	user := &models.User{}
	if err := tx.Find(user, targetUserID); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Generate OTP
	rand.Seed(time.Now().UnixNano())
	otp := strconv.Itoa(rand.Intn(900000) + 100000)
	user.OTPCode = otp
	// user.OTPExpiresAt = time.Now().Add(10 * time.Minute) // Model update needed if we want strict expiry check here too

	// Use Raw Query to force update of OTP (bypass validation just in case)
	// But standard Update should work if validations pass. Let's try standard first.
	// Actually, let's use the Raw Query pattern we found reliable in Auth.
	q := tx.RawQuery("UPDATE users SET otp_code = ? WHERE id = ?", otp, user.ID)
	if err := q.Exec(); err != nil {
		c.Logger().Error("Failed to update OTP for delete", err)
		return err
	}

	// SIMULATE EMAIL
	c.Logger().Infof("\n\n=== DELETE ACCOUNT OVERRIDE OTP ===\nTO: %s\nCODE: %s\n================================\n", user.Email, otp)

	c.Flash().Add("success", "OTP sent. Please confirm deletion.")
	return c.Redirect(http.StatusSeeOther, "/account/delete/confirm/%s", user.ID)
}

// ConfirmDeletePage renders the OTP entry form for deletion
func (v UsersResource) ConfirmDeletePage(c buffalo.Context) error {
	// AUTH CHECK
	currentUserID := c.Session().Get("current_user_id")
	targetUserID := c.Param("user_id")
	if currentUserID == nil || fmt.Sprintf("%v", currentUserID) != targetUserID {
		c.Flash().Add("danger", "Unauthorized.")
		return c.Redirect(http.StatusSeeOther, "/")
	}

	// Pass user ID to template
	c.Set("user_id", targetUserID)
	return c.Render(http.StatusOK, r.HTML("users/confirm_delete.plush.html"))
}

// New renders the form for creating a new User.
// This function is mapped to the path GET /users/new
func (v UsersResource) New(c buffalo.Context) error {
	c.Set("user", &models.User{})
	return c.Render(http.StatusOK, r.HTML("users/new.plush.html"))
}
